controller_manager:
  ros__parameters:
    update_rate: 50

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50

diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_joints: ["joint_wheel_fl", "joint_wheel_rl"]
    right_joints: ["joint_wheel_fr", "joint_wheel_rr"]
    wheel_separation: 0.70
    wheel_radius: 0.165
    cmd_vel_timeout: 0.25
    open_loop: false
    pose_covariance_diagonal: [0.0001, 0.0001, 0.0001]
